# Generated by Django 5.2.8 on 2025-11-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="participante",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="static/main/img"),
        ),
    ]
