# Generated by Django 5.2.8 on 2025-11-18 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_participante_foto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Encuesta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pregunta", models.CharField(max_length=300)),
                ("activa", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="RetoUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("puntos_recompensa", models.IntegerField(default=10)),
                ("activo", models.BooleanField(default=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("votar", "Votar"),
                            ("alianza", "Alianza"),
                            ("constancia", "Constancia"),
                        ],
                        max_length=50,
                    ),
                ),
                ("parametro", models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name="participante",
            name="eliminado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reto",
            name="puntos",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="participante",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="participantes/"),
        ),
        migrations.CreateModel(
            name="ObjetivoDonacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("puntos_necesarios", models.IntegerField(default=100)),
                ("puntos_actuales", models.IntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "participante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.participante",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OpcionEncuesta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.CharField(max_length=200)),
                ("votos", models.IntegerField(default=0)),
                (
                    "encuesta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opciones",
                        to="main.encuesta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DonacionUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puntos_donados", models.IntegerField(default=0)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "objetivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.objetivodonacion",
                    ),
                ),
            ],
            options={
                "unique_together": {("usuario", "objetivo")},
            },
        ),
    ]
