# Generated by Django 5.2.8 on 2025-11-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_encuesta_retousuario_participante_eliminado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reto",
            name="completado",
            field=models.BooleanField(default=False),
        ),
    ]
